config/routes.rb
Basemap::Application.routes.draw do
  resources :polygons

  root :to => "polygons#index"

end

app/models/polygon.rb
class Polygon < ActiveRecord::Base
  MAX_AREA_KM2 = 9000
  DEFAULT_SRID = 4326

  def self.geojson_data id
    ActiveRecord::Base.connection.select_one(
    "SELECT id, x(ST_PointOnSurface(geometry::geometry)) as lng,
              y(ST_PointOnSurface(geometry::geometry)) as lat,
              ST_AsGeoJSON(geometry::geometry,6,0) as geojson
              FROM polygons AS p
              WHERE p.id=#{id}"
    )
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/polygons_controller.rb
class PolygonsController < ApplicationController
  # GET /polygons
  def index
    @polygons = Polygon.all
  end

  # GET /polygons/new
  def new
    @polygon = Polygon.new

    @submission_url = "/polygons"
    @submission_http_verb = "POST"

    render :action => :new, :layout => "map"
  end

  # GET /polygons/1/edit
  def edit
    id = params[:id]
    @geojson_data = Polygon.geojson_data(id).to_json

    @submission_url = "/polygons/#{id}"
    @submission_http_verb = "PUT"

    render :action => :edit, :layout => "map"
  end

  # POST /polygons
  def create
    begin
      @polygon = Polygon.create! :geometry => PolygonsHelper.parse_geom(params[:geometry])
    rescue Exception => e
      msg = "Polygon couldn't be uploaded: #{e.message}"
      Rails.logger.fatal "#{msg} (#{e.class})"
      render :json => {:error => msg}
    else
      render :json => {:id => @polygon.id}
    end
  end

  # PUT /polygons/1
  def update
    @polygon = Polygon.find(params[:id])


    begin
      @polygon.geometry = PolygonsHelper.parse_geom params[:geometry]
      @polygon.save!
    rescue Exception => e
      msg = "Polygon couldn't be saved: #{e.message}"
      Rails.logger.fatal "#{msg} (#{e.class})"
      render :json => {:error => msg}
    else
      render :json => {:id => @polygon.id}
    end
  end

  # DELETE /polygons/1
  def destroy
    @polygon = Polygon.find(params[:id])
    @polygon.destroy

    redirect_to(polygons_url)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/polygons_helper.rb
module PolygonsHelper
  # todo: multiple geometries?
  def self.parse_geom geojson
    polygon_wkt = GeomHelper.geojson_to_wkt geojson
    validate_max_area polygon_wkt
    wkb = ActiveRecord::Base.connection.execute("SELECT ST_GeomFromText('#{polygon_wkt}')")
    wkb.getvalue(0, 0)
  end

  def self.validate_max_area polygon_wkt, srid = Polygon::DEFAULT_SRID
    area = ActiveRecord::Base.connection.select_value("SELECT (ST_Area(ST_Transform(ST_GeomFromText('#{polygon_wkt}',#{srid}),954009)))").to_i
    area = area / 1000000 .to_i
    if area <= Polygon::MAX_AREA_KM2
      return true
    end
    raise "Your polygon is too large (#{area} km2), please limit its area to #{Polygon::MAX_AREA_KM2} km2."
    redirect_to root_url
  end
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Basemap</title>
  <%= stylesheet_link_tag 'scaffold' %>
  <%#= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  <%= favicon_link_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/layouts/map.html.erb
<!DOCTYPE html>
<html>
<head>
  <meta http-equiv="Content-type" content="text/html; charset=utf-8"/>
  <title>Basemap</title>
  <%= favicon_link_tag %>

  <%= stylesheet_link_tag 'site', 'map' %>
  <%= csrf_meta_tag %>

  <!-- JAVASCRIPT GOES HERE -->
  <%= javascript_include_tag(
              "http://maps.google.com/maps/api/js?sensor=true#{"&libraries=geometry" if Polygon::MAX_AREA_KM2}",
              'http://www.google.com/jsapi',
              'http://ajax.googleapis.com/ajax/libs/jquery/1.4.3/jquery.min.js',
              'http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/jquery-ui.js',
              'jquery.json-2.2.js',
              'application',
              'map'
      ) %>
  <script type="text/javascript">
      MAX_POLYGON_AREA_KM2 = <%= Polygon::MAX_AREA_KM2 %>;
      var submission_target = {
          url: '<%= @submission_url %>',
          <%= "http_verb: '#{@submission_http_verb}'," if @submission_http_verb %>
      };
  </script>
</head>
<body>
<a id="zoomIn"></a>
<a id="zoomOut"></a>

<div id="map_tools">
  <h3>Tools</h3>

  <div class="buttons">
    <a id="done" class="disabled" onclick="submitPolygon(); return false;" href="#"></a>
  </div>
  <div class="shader"></div>
</div>

<%= yield %>

<div style="position:absolute; top:0; left:0; width:100%; height:100%">
  <div id="map_canvas" style="z-index:1; position:absolute; top:0; left:0; right:0; bottom:0; height:100%"></div>
</div>

<div id="container" style="position:absolute; bottom:0; left:0; width: 100%; height:30%; display:none;"></div>

</body>
</html>

app/views/polygons/_form.html.erb
<%= form_for(@polygon) do |f| %>
  <% if @polygon.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@polygon.errors.count, "error") %> prohibited this polygon from being saved:</h2>

      <ul>
      <% @polygon.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :geometry %><br />
    <%= f.text_field :geometry %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/polygons/edit.html.erb
<div id="map_data"><%= raw @geojson_data %></div>

app/views/polygons/index.html.erb
<h1>Listing polygons</h1>

<table>
  <tr>
    <th>Geometry</th>
    <th></th>
    <th></th>
  </tr>

<% @polygons.each do |polygon| %>
  <tr>
    <td><%= link_to 'Edit', edit_polygon_path(polygon) %> #<%= polygon.id %></td>
    <!--<td><%= link_to 'Destroy', polygon, :confirm => 'Are you sure?', :method => :delete %></td>-->
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Polygon', new_polygon_path %>